name: hyrwbz_frontend
description: 会议任务管理跟踪系统 - Flutter 前端
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  pinyin: ^3.3.0
  file_picker: ^8.0.0
  window_manager: ^0.4.2
  screen_retriever: 0.2.2
  dart_ipc: 1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
